services:
  - type: web
    name: telegram_bot_worker
    runtime: docker
    repo: https://github.com/aErixxx/telegram_bot_worker
    branch: main
    dockerfilePath: ./Dockerfile
    plan: free
    numInstances: 1
    envVars:
      - key: PYTHON_VERSION
        value: "3.13"
      - key: PORT
        value: "8000"
